package com.centauri.equations.util;

public enum Polygon {

    // 2D shapes
    TRIANGLE, QUADRILATERAL, PENTAGON, SQUARE, RECTANGLE, TRAPEZOID, CIRCLE, ELLIPSE, SECTOR,

    // 3D shapes
    CONE, CUBE, CYLINDER, PYRAMID, RECTANGULAR_PRISM, SPHERE, TRAPEZIODAL_PRISM, TRIANGULAR_PRISM, TRIANGULAR_PYRAMID,

}
